# Generated by Django 4.1.5 on 2023-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bloodpressure', models.CharField(max_length=255)),
                ('bp2', models.CharField(max_length=255)),
            ],
        ),
    ]
